kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-sostrades-conf

data:
  my.cnf: |-

    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/mysql
    plugin_dir=/opt/mysql/lib/plugin
    port=3306
    socket=/opt/mysql/tmp/mysql.sock
    datadir=/mysql/data
    tmpdir=/opt/mysql/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/opt/mysql/tmp/mysqld.pid
    log-error=/opt/mysql/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci

    [client]
    port=3306
    socket=/opt/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/mysql/lib/plugin

    [manager]
    port=3306
    socket=/opt/mysql/tmp/mysql.sock
    pid-file=/opt/mysql/tmp/mysqld.pid
